/* Generated By:JavaCC: Do not edit this line. JayParserConstants.java */
package tleng.tp.grammar;

public interface JayParserConstants {

  int EOF = 0;
  int KWBOOLEAN = 6;
  int KWELSE = 7;
  int KWIF = 8;
  int KWINT = 9;
  int KWMAIN = 10;
  int KWVOID = 11;
  int KWWHILE = 12;
  int LITERAL = 13;
  int BOOLEAN = 14;
  int INTEGER = 15;
  int LL_A = 16;
  int LL_C = 17;
  int PAR_A = 18;
  int PAR_C = 19;
  int PTOCOMA = 20;
  int COMA = 21;
  int IDENTIFIER = 22;
  int LETRA = 23;
  int DIGITO = 24;
  int OASSIGN = 25;
  int OPLUS = 26;
  int OMINUS = 27;
  int OSTAR = 28;
  int OSLASH = 29;
  int OMENOR = 30;
  int OMAYOR = 31;
  int OADMIRACION = 32;
  int OAND = 33;
  int OOR = 34;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"boolean\"",
    "\"else\"",
    "\"if\"",
    "\"int\"",
    "\"main\"",
    "\"void\"",
    "\"while\"",
    "<LITERAL>",
    "<BOOLEAN>",
    "<INTEGER>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<IDENTIFIER>",
    "<LETRA>",
    "<DIGITO>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
  };

}
