/* Generated By:JavaCC: Do not edit this line. AdderParserConstants.java */
package tleng.tp.samples.adder.grammar;

public interface AdderParserConstants {

  int EOF = 0;
  int PLUS = 5;
  int NUMBER = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"+\"",
    "<NUMBER>",
  };

}
